# Generated by Django 4.1.3 on 2022-11-24 15:54

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareanalysis',
            name='status',
            field=models.JSONField(default=uploader.models.jsonfield_default_value),
        ),
    ]
