# Generated by Django 4.1.3 on 2022-12-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porter', '0002_initial'),
        ('uploader', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareanalysis',
            name='log_size',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='firmwareanalysis',
            name='zip_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='porter.logzipfile'),
        ),
    ]
