# Generated by Django 4.1.3 on 2022-11-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareanalysis',
            name='status',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(blank=True, help_text='label name', max_length=127, unique=True, verbose_name='label name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Vendor name', max_length=127, unique=True, verbose_name='vendor name'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_name', 'device_vendor')},
        ),
    ]
