# Generated by Django 4.1.3 on 2022-12-13 08:26

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_firmwareanalysis_log_size_firmwareanalysis_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareanalysis',
            name='status',
            field=models.JSONField(default=uploader.models.jsonfield_default_value),
        ),
        migrations.AlterField(
            model_name='firmwareanalysis',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
