# Generated by Django 4.1.3 on 2022-11-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_firmwareanalysis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareanalysis',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
