# Generated by Django 4.1.5 on 2023-05-12 08:38

from django.db import migrations, models
import django.utils.datetime_safe
import porter.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogZipFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('file', models.FileField(upload_to=porter.models.LogZipFile.get_storage_path)),
            ],
        ),
    ]
