# Generated by Django 4.1.3 on 2022-11-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='firmware_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.firmwareanalysis'),
        ),
    ]
