# Generated by Django 5.1.7 on 2025-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                blank=True, help_text="API key of the user", max_length=64, null=True
            ),
        ),
    ]
