# Generated by Django 5.1.7 on 2025-05-03 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='config_id',
            field=models.CharField(blank=True, help_text='Configuration ID of the user', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_private_key', models.TextField(blank=True, help_text='SSH private key to access worker nodes', null=True)),
                ('ip_range', models.TextField(blank=True, help_text='IP range of the worker nodes', null=True)),
                ('user', models.ForeignKey(help_text='User who created this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
