# Generated by Django 5.1.7 on 2025-05-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_config_id_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the configuration', max_length=150, null=True),
        ),
    ]
