# Generated by Django 5.1.7 on 2025-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_configuration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='ssh_private_key',
        ),
        migrations.AddField(
            model_name='configuration',
            name='ssh_password',
            field=models.CharField(blank=True, help_text='SSH password of the worker nodes', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ssh_user',
            field=models.CharField(blank=True, help_text='SSH user of the worker nodes', max_length=150, null=True),
        ),
    ]
